server:
  port: 32001


spring:
  application:
    name: daka
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.9:3306/daka?ucharacterEncoding=UTF8&allowLoadLocalInfile=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # ????????????????????????????????????SQLException???30?
      connection-timeout: 30000
      # ?????
      minimum-idle: 5
      # ?????
      maximum-pool-size: 15
      # ????
      auto-commit: true
      # ????idle???????????????????retired),??10??
      idle-timeout: 600000
      # ??????
      pool-name: DatebookHikariCP
      # ???????????????????????????retired),??30??1800000ms
      max-lifetime: 28740000
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl